# Generated by Django 2.2.1 on 2019-06-15 12:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('taskmain', '0002_auto_20190612_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2019, 6, 22, 12, 27, 38, 797399)),
        ),
    ]
